// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOTA74J4Xws7SoP3ADNKqqR51DWaKHx0',
    appId: '1:459488155267:web:d90dc882b05e5c0c1d6db6',
    messagingSenderId: '459488155267',
    projectId: 'bree-firebase',
    authDomain: 'bree-firebase.firebaseapp.com',
    storageBucket: 'bree-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XglODSzbLq1WztaxqxQ4OHpi1uQlldo',
    appId: '1:459488155267:android:b39ea83d7fb500ee1d6db6',
    messagingSenderId: '459488155267',
    projectId: 'bree-firebase',
    storageBucket: 'bree-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAayZq1vPzDkp3_DPw6EWtP90i3p77MBIk',
    appId: '1:459488155267:ios:578b0376876850011d6db6',
    messagingSenderId: '459488155267',
    projectId: 'bree-firebase',
    storageBucket: 'bree-firebase.appspot.com',
    iosBundleId: 'com.example.eCommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAayZq1vPzDkp3_DPw6EWtP90i3p77MBIk',
    appId: '1:459488155267:ios:578b0376876850011d6db6',
    messagingSenderId: '459488155267',
    projectId: 'bree-firebase',
    storageBucket: 'bree-firebase.appspot.com',
    iosBundleId: 'com.example.eCommerceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoOTA74J4Xws7SoP3ADNKqqR51DWaKHx0',
    appId: '1:459488155267:web:6e021c7060c920a41d6db6',
    messagingSenderId: '459488155267',
    projectId: 'bree-firebase',
    authDomain: 'bree-firebase.firebaseapp.com',
    storageBucket: 'bree-firebase.appspot.com',
  );

}